apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: json-editor
  description: Json validator service
  tags:
    - json
    - validators
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform-engineering
  system: packages
